# Generated by Django 5.2.3 on 2025-07-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='',
        ),
    ]
