# Generated by Django 5.2.3 on 2025-07-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_authuser_options_alter_authuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
    ]
